name: say hello

on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: echo del mensaje
        run:
          echo "hola mundo!"
      - name: dime la fecha
        run: date
      - run: ls -l